repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
        name: Merge conflict protection
        stages: [pre-commit]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.25.0
    hooks:
      - id: commitizen
        name: Commit message enforcement
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: tflint
        name: terraform linting
        stages: [pre-commit]
        entry: make tf-lint
        language: system
  - repo: local
    hooks:
      - id: terraform-validate
        name: terraform validation
        stages: [pre-commit]
        entry: make tf-validate
        language: system
  - repo: local
    hooks:
      - id: security-scan
        name: Security standards enforcement
        stages: [pre-commit]
        entry: make sec-scan
        language: system
