name: Quality gate
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
  workflow_dispatch:
permissions: read-all
jobs:
  security-scan:
    name: Security scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: checkov-scan
        name: Checkov scan
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli
          output_file_path: console
          file: .config/.checkov.yaml
