name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  issues: write
  pull-requests: write
  deployments: write
jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - id: setup-node
        uses: StoopidCompany/node-inator/.github/actions/node-inator@main
        with:
          node-version: 20

      - id: release
        name: Release tag to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        run: npx semantic-release
